
all: run-tests

RVSIM := bin/rvsim
TESTROOT := ../riscv-arch-test
BUILDDIR := tests

V ?= @

RISCV_PREFIX := /work/riscv/toolchains/riscv32-elf-7.3.0-Linux-x86_64/bin/riscv32-elf-
#RISCV_PREFIX   := riscv32-unknown-elf-

RISCV_GCC      := $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  := $(RISCV_PREFIX)objdump
RISCV_OBJCOPY  := $(RISCV_PREFIX)objcopy
RISCV_NM       := $(RISCV_PREFIX)nm
RISCV_CFLAGS   := -g -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles
RISCV_CFLAGS   += -march=rv32im -mabi=ilp32 -DXLEN=32 -Ttarget/link.ld
RISCV_CFLAGS   += -I$(TESTROOT)/riscv-test-env -I$(TESTROOT)/riscv-test-env/p -Itarget

TESTSUITE := $(TESTROOT)/riscv-test-suite
TESTGROUPS := rv32i_m/I rv32i_m/M

ALL :=

# $1 = source/test.S, $2 = source/test.sig, $3 = build/test
define test-template
$(3).elf: $(1)
	@mkdir -p $$(dir $$@)
	@echo MAKE: $$@
	$(V)$(RISCV_GCC) $(RISCV_CFLAGS) -o $$@ $$<

$(3).bin: $(3).elf
	$(V)$(RISCV_OBJCOPY) -O binary $$< $$@

$(3).lst: $(3).elf
	$(V)$(RISCV_OBJDUMP) -D $$< > $$@

$(3).map: $(3).elf
	$(V)$(RISCV_NM) $$< > $$@

$(3).pass: $(3).bin $(3).map $(3).lst
	@echo TEST: $(3)
	$(V)$(RVSIM) $$< -dump=$(3).sig \
	-from=$$$$(grep begin_signature $(3).map | awk '{print $$$$1}') \
	-to=$$$$(grep end_signature $(3).map | awk '{print $$$$1}') \
	2> $(3).log 1>&2
	$(V)if diff $(3).sig $(2) > $(3).diff ;\
	then echo PASS: $(3) ; touch $$@ ;\
	else echo FAIL: $(3) ; exit 1 ; fi

.PRECIOUS: $(3).elf $(3).bin $(3).lst $(3).map $(3).log $(3).sig $(3).diff

ALL += $(3).pass
endef

$(foreach grp,$(TESTGROUPS),\
$(foreach src,$(wildcard $(TESTSUITE)/$(grp)/src/*.S),\
$(eval $(call test-template,$(src)\
,$(patsubst $(TESTSUITE)/$(grp)/src/%.S,$(TESTSUITE)/$(grp)/references/%.reference_output,$(src))\
,$(patsubst $(TESTSUITE)/$(grp)/src/%.S,$(BUILDDIR)/$(grp)/%,$(src))))))

run-tests: $(ALL)
